### ISSUE TITLE
Filename conflict under Windows

### ISSUE THREAD

**Issue by rchastain** [t-edson/UnTerminal#1]
Hello!

When I unzip the UnTerminal archive I get a warning because of two files having the same name ("Parser.pas" and "parser.pas"). I had to compare the two files and decided that "Parser.pas" was the good one. :)
I experimented the same problem with some other of your packages (for example with "Gencod.pas" in Tito's Terminal, if I remember correctly).

Regards.

Roland

**Comment by t-edson** [comment]
Hi. Are you compiling the /TTerm project?
Probably it has many errors. I haven't updated it to the last versions. In fact I have deleted in the new revisions of UnTerminal. It was the previous attempt for my program: https://github.com/t-edson/Tito-s-Terminal
Thanks for checking.

**Comment by rchastain** [comment]
Yes, I was speaking of TTerm.

Yes, I saw that it is a old version of Tito's Terminal. Sometimes a simpler version is good. Tito's Terminal has many functions that I will probably never use (lack of knowledge).

In Tito's Terminal there is also an issue (under Windows) with two files having the same name.

Happy new year!

Regards.

Roland

**Comment by t-edson** [comment]
Please, report the issue in Tito's Terminal GitHub, to fix it. Happy New Year.

**Comment by rchastain** [comment]
Hello!

The issue of the file names is present in several of your packages. If I report it one time, isn't it enough? Under Windows, you can't have two files with the same name, for example "Parser.pas" and "parser.pas". So if you want to give access to your projects to Windows users, you have to avoid to have two files with the same name. When I cloned Unterminal repository to my disk, one of the files was simply overwritten, without any warning from Github application!

I tried to compile Tito's Terminal (using the libraries downloaded from your repositories), but there were too many problems and I finally gave up. Certainly it's because of modifications in the libraries not reported in Tito's Terminal source code. If some day you update that project, I would suggest to include the libraries in Tito's Terminal repository, so that the project still stay compilable even if you modify a library.

For me, as I said, I am more interested by UnTerminal, and the old TTerm demo is enough for my needs. But I always keep an eye on your other (very interesting) projects. ;)

Regards.

Roland

**Comment by t-edson** [comment]
Yes. I forgot sometimes to delete old versions of files. I've deleted a duplicated file in Tito's Terminal, and updated the source to the new versions of library. 
You can ask me for the problems compiling Tito's Terminal. I don't include the libraries because those are independent projects but I can make a capture of the libraries if it's needed.

**Comment by rchastain** [comment]
Hello! Thank you for your commits to Tito's Terminal. But I still get the same errors. Yes, I would like to have the libraries that you actually used to compile that project.
Regards.
Roland

**Comment by rchastain** [comment]
In the repository of my chess GUI (Eschecs), I included all the libraries (fpGUI, BGRABitmap...). You can compile the project with a simple command line, if you have Free Pascal installed.
But if you provide a link to the files somewhere, it's OK. :)

**Comment by t-edson** [comment]
OK. I will include a copy of libraries in next versions.
