### ISSUE TITLE
powershell hangs on while executing 

### ISSUE THREAD

**Issue by zux0x3a** [t-edson/UnTerminal#3]
that happens only in some windows builds especially red stone, while execution of PowerShell it only appears the logo and hangs 
on so nothing happens and can't pass or execute commands 

```
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.
```

**Comment by t-edson** [comment]
Hi. I don't have Windows 10 Redstone to test. I've tested in Windows 10 and it works right. 
Maybe you're not sending the proper CR/LF line delimiter.
Do you have a sample project to test in my Windows version?

**Comment by zux0x3a** [comment]
I think that's related to an issue on previous PowerShell versions, so the main problem is that all Process components, not just your script failed to capture process output when the prompt line was initiated. so I would say it is a major bug 
if you asking me how many systems are affected I would say : 

Windows 10 (10240) 
Windows 7
