### ISSUE TITLE
Can do redirect another program input and output in windows console program ?

### ISSUE THREAD

**Issue by sum2012** [t-edson/UnTerminal#4]
@t-edson 
I asked GTP-4 but fail to use this library.

use free pascal programming language using UnTerminal library from https://github.com/t-edson/UnTerminal to write a windows 
console of chinese chess program （orgucci.exe） which only interface Universal Chinese Chess Protocol （ucci ）,all ucci commands redirect to another ucci program （eleeye.exe）,orgucci.exe can send back data to console from eleeye.exe.

**Comment by t-edson** [comment]
I'm afraid I don't understand well what do you want to do. If you refer to be able to execute something like "program1.exe <  program2.exe" or  "program1.exe |  program2.exe", it's not possible to do directly in UnTerminal. Maybe you can create some script in a *.bat file that do the redirection, and then execute that *.bat file.

**Comment by rchastain** [comment]
If I understand correctly, @sum2012 would like a program similar to [this one](https://forum.lazarus.freepascal.org/index.php/topic,25735.msg471086.html#msg471086), but a console program.

**Comment by sum2012** [comment]
I find another GTP that give me answer that without  UnTerminal library.
Code: 
https://gist.github.com/sum2012/a64478bde210ac40c110f5e4cbdc9f98

**Comment by sum2012** [comment]
@rchastain Yes, similar to that one,the chinese chess engine only use 1 thread,I want to use this method to make it multi thread that without modify the source.

**Comment by rchastain** [comment]
@sum2012 
You could also take a look to [this demo](https://sourceforge.net/p/lazarus-ccr/svn/HEAD/tree/examples/process/) using FPC Process unit. (I built my [chess GUI](https://gitlab.com/rchastain/eschecs) on that demo.)

But it would also be interesting to have an example of console program using UnTerminal, if it is possible.

**Comment by sum2012** [comment]
@rchastain I ask perplexity.ai to give the code for using TProcess  .
https://www.perplexity.ai/search/3d2199fe-d837-4071-b9fe-4770d3ae0152?s=u
UnTerminal will be try later

**Comment by sum2012** [comment]
Tried UnTerminal library,but fail

**Comment by t-edson** [comment]
Have you tested the sample programs of UnTerminal? Do they help you or, what's the problem with that demos?

**Comment by sum2012** [comment]
Yes,Modify of example 3
https://gist.github.com/sum2012/29163672a1085aed699f6acd31b2f319
After input "dir",display information in console ,then the program freeze
![1](https://github.com/t-edson/UnTerminal/assets/2177532/b7d5726b-548b-43ae-a8dc-5a63f0977f7f)

**Comment by sum2012** [comment]
Change to p.proc.Loop(1); seem work
