### ISSUE TITLE
Non-latin characters cannot display correctly.

### ISSUE THREAD

**Issue by PerfBleu** [t-edson/UnTerminal#6]
![屏幕截图 2023-06-04 232036](https://github.com/t-edson/UnTerminal/assets/38901384/b5463095-8cb6-45a7-83a0-3ff8041e1f3b)
like the picture above

**Comment by t-edson** [comment]
Hi. That's because console and LCL don't use the same character encoding. I've the same problem, even with Latin characters.
I solved it using the function ConsoleToUTF8() before all the text added or updated to the TMemo.
ConsoleToUTF8() is declared in the unit LazUTF8.

**Comment by PerfBleu** [comment]
> Hi. That's because console and LCL don't use the same character encoding. I've the same problem, even with Latin characters. I solved it using the function ConsoleToUTF8() before all the text added or updated to the TMemo. ConsoleToUTF8() is declared in the unit LazUTF8.

Thank you very much!
