### ISSUE TITLE
accented characters

### ISSUE THREAD

**Issue by Black4nge1** [t-edson/UnTerminal#8]
Thanks for your nice work. Much better than TProcess or TProcessUTF8. But when start a CMD, it has incorrect accented characters. If i start a program in open cmd, like ffmpeg, the command cannot handle filenames with accented characters. In your screen example you can see the incorrect accented exit in CMD.

**Comment by Black4nge1** [comment]
I decided to pre create .cmd files with the instructions chcp 65001 and ::UTF8 at the beginning and then sending them to SendLn(). It worked with accents. I leave this tip for anyone who has the same problem.

**Comment by t-edson** [comment]
Hi. I think this is related to https://github.com/t-edson/UnTerminal/issues/6
